---

- name: Enable PostgreSQL repo
  yum:
    name: "{{ postgresql_repo }}"
    state: present

- name: Install PostgreSQL packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql_packages }}"

- name: Install PostgreSQL python libraries
  yum:
    name: python-psycopg2
    state: present
