---
# tasks file for postgresql

- name: Include distro-specific variables
  include_vars:
    file: "{{ item }}"
  with_items: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- include: install.yml
  tags: install

- include: initialize.yml
  tags: initialize

- name: Start and enable PostgreSQL
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: true

- include: databases.yml
  tags: database

- include: users.yml
  tags: users
